Repository stepmania/stepmania, pull requests merged in 2020-09, with the labels that each got.

#2053 give CryptManager and Lua access to tomcrypt's SHA256
  Docs/Luadoc/Lua.xml
  Docs/Luadoc/LuaDocumentation.xml
  extern/CMakeProject-tomcrypt.cmake
  src/CryptManager.cpp
  src/CryptManager.h
  src/RageUtil.cpp
Labels: enhancement, needs testing

#2056 add preference to change PacDrive light ordering
  src/arch/Lights/LightsDriver_PacDrive.cpp
Labels: arcade

#2043 Fix -Wreturn-type and its undefined behavior
  src/NotesWriterSM.cpp
Labels: bug fix
